name: Ember Observer
on:
  pull_request: {}
  push:
    branches:
      - main
    tags:
      - v*
  schedule:
    - cron: '0 0 * * *'

jobs:
  ember-debug:
    name: Build ember-debug
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Volta
        uses: volta-cli/action@v1
      - name: Install dependencies (yarn)
        run: yarn install --non-interactive --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: ember-debug
          path: dist

  test:
    name: Test (${{ matrix.scenario }})
    needs: ember-debug
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/ember-observer
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - default
          - release
          - beta
          - canary
          - lts-3.16
          - lts-3.20
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download ember-debug
        uses: actions/download-artifact@v2
        with:
          name: ember-debug
          path: dist
      - name: Set up Volta
        uses: volta-cli/action@v1
      - name: Install dependencies
        run: yarn install --non-interactive --no-lockfile
      - name: Setup ember-try scenario
        if: matrix.scenario != 'default'
        run: >-
          yarn ember try:one ember-${{ matrix.scenario }} --skip-cleanup ---
          '[ -z "$EMBER_OPTIONAL_FEATURES" ] || echo "::set-env name=EMBER_OPTIONAL_FEATURES::$EMBER_OPTIONAL_FEATURES"'
      - name: Build
        run: yarn ember build --environment test
      - name: Run test (ember-debug)
        # Due to a bug in ember-cli, running `ember test` with `--path` doesn't set `EMBER_ENV=test`
        # See https://github.com/ember-cli/ember-cli/issues/8922
        run: EMBER_ENV=test yarn ember test --filter ember-debug --path dist
      - name: Run test (ember-observer)
        # Due to a bug in ember-cli, running `ember test` with `--path` doesn't set `EMBER_ENV=test`
        # See https://github.com/ember-cli/ember-cli/issues/8922
        run: EMBER_ENV=test yarn ember test --filter '!ember-debug' --path dist
